from project.language import translate, language


def autogeneration(request):
    lang = language(request)
    return {
        "group_selection": translate("Выбор группы", lang),
        "analysis": translate("Анализ", lang),
        "topics": translate("Темы", lang),
        "content_plan": translate("Контент-план", lang),
        "posts": translate("Посты", lang),
        "card_title": translate("Выберите группу для анализа", lang),
        "group_analysis": translate("Анализ группы", lang),
        "selected_group": translate("Выбранная группа", lang),
        "subscribers": translate("Подписчиков", lang),
        "add_new_group": translate("Добавить новую группу", lang),
        "add_for_analysis": translate("Подключите новую группу или страницу для анализа", lang),
        "next": translate("Далее", lang),
        "back_to_posts": translate("Назад к постам", lang),
        "marketing": translate("Маркетинг и реклама", lang),
        "interior_design": translate("Дизайн интерьера", lang),
        "it_and_technologys": translate("IT и технологии", lang),
        "analyses_cost": translate("Стоимость анализа", lang),
        "group_cost": translate("Анализ этой группы будет стоить", lang),
        "coins": translate("коинов", lang),
        "run_analysis": translate("Запустить анализ группы", lang),
        "analysis_complete": translate("Анализ завершён", lang),
        "new_gtoup_addition ": translate("Добавление новой группы", lang),
        "group_name": translate("Название группы", lang),
        "group_url": translate("URL группы", lang),
        "platform": translate("Платформа", lang),
        "cancel": translate("Отмена", lang),
        "add_group": translate("Добавить группу", lang),
        "post_editing": translate("Редактирование поста", lang),
        "group_title": translate("Заголовок", lang),
        "post_content": translate("Содержание поста", lang),
        "hashtags": translate("Хештеги", lang),
        "hashtags_separation": translate("Разделяйте хештеги пробелами", lang),
        "publication_date": translate("Дата публикации", lang),
        "publication_time": translate("Время публикации", lang),
        "image": translate("Изображение", lang),
        "image_generation": translate("Сгенерировать новое изображение", lang),
        "group_posts_analysis": translate("Анализ постов группы", lang),
        "loading": translate("Загрузка", lang),
        "main_group_topics": translate("Основные темы группы", lang),
        "back": translate("Назад", lang),
        "post_topics": translate("Темы для постов", lang),
        "add_topic": translate("Добавить тему", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
    }