from project.language import translate, language


def autogeneration(request):
    lang = language(request)
    return {
        "group_selection": translate("Выбор группы", lang),
        "analysis": translate("Анализ", lang),
        "topics": translate("Темы", lang),
        "content_plan": translate("Контент-план", lang),
        "posts": translate("Посты", lang),
        "card_title": translate("Выберите группу для анализа", lang),
        "group_analysis": translate("Анализ группы", lang),
        "selected_group": translate("Группа", lang),
        "subscribers": translate("Подписчиков", lang),
        "add_new_group": translate("Добавить новую группу", lang),
        "add_for_analysis": translate("Подключите новую группу или страницу для анализа", lang),
        "next": translate("Далее", lang),
        "back_to_posts": translate("Назад к постам", lang),
        "marketing": translate("Маркетинг и реклама", lang),
        "interior_design": translate("Дизайн интерьера", lang),
        "it_and_technologys": translate("IT и технологии", lang),
        "analyses_cost": translate("Стоимость анализа", lang),
        "group_cost": translate("Анализ этой группы будет стоить", lang),
        "coins": translate("коинов", lang),
        "run_analysis": translate("Запустить анализ группы", lang),
        "analysis_complete": translate("Анализ завершён", lang),
        "new_gtoup_addition ": translate("Добавление новой группы", lang),
        "group_name": translate("Название группы", lang),
        "group_url": translate("URL группы", lang),
        "platform": translate("Платформа", lang),
        "cancel": translate("Отмена", lang),
        "add_group": translate("Добавить группу", lang),
        "post_editing": translate("Редактирование поста", lang),
        "group_title": translate("Заголовок", lang),
        "post_content": translate("Содержание поста", lang),
        "hashtags": translate("Хештеги", lang),
        "hashtags_separation": translate("Разделяйте хештеги пробелами", lang),
        "publication_date": translate("Дата публикации", lang),
        "publication_time": translate("Время публикации", lang),
        "image": translate("Изображение", lang),
        "image_generation": translate("Сгенерировать новое изображение", lang),
        "group_posts_analysis": translate("Анализ постов группы", lang),
        "loading": translate("Загрузка", lang),
        "main_group_topics": translate("Основные темы группы", lang),
        "back": translate("Назад", lang),
        "post_topics": translate("Темы для постов", lang),
        "add_topic": translate("Добавить тему", lang),
        "generate_content_plan": translate("Сгенерировать контент-план", lang),
        "advice": translate("Совет", lang),
        "generated_post": translate("Сгенерированные посты", lang),
        "generate_post": translate("Сгенерировать посты", lang),
        "regenerate": translate("Сгенерировать заново", lang),
        "ready": translate("Готово", lang),
        "new_topic": translate("Новая тема", lang),
        "new_topic_description": translate("Описание новой темы", lang),
        "analysis_results": translate("Результаты анализа", lang),
        "plan_everything": translate("Запланировать всё", lang),
        "save_everything": translate("Сохранить всё", lang),
        "wait": translate("Пожалуйста, подождите", lang),
        "main_topics": translate("Определение основных тем", lang),
        "aaa": translate("Анализ активности аудитории", lang),
        "complete_analysis": translate("Завершение анализа", lang),
        "or": translate("ИЛИ", lang),
        "re_run": translate("Провести анализ заново", lang),
        "prew_analyse": translate("Вы можете выбрать темы на основе предыдущего анализа от", lang),
        "get_prew_analysis_tags": translate("Взять темы предыдущего анализа", lang),
        "analysis_backward_reset": translate("Данные анализа группы сохранены. Вы можете вернутся к ним по кнопке Взять темы предыдущего анализа", lang),
        "posts_successfully_scheduled": translate("Все посты успешно запланированы", lang),
        "posts_planning": translate("Планирование постов...", lang),
        "posts_saveing": translate("Сохранение постов...", lang),
        "posts_have_been_saved": translate("Все посты успешно сохранены", lang),
        "network_error": translate("Ошибка сети", lang),
        "server_error": translate("Сервер вернул ошибку", lang),
        "send_content_plan": translate("Контент-план успешно отправлен", lang),
        "cp_sub": translate("Отправка контент-плана...", lang),
        "fail_cp": translate("Не удалось отправить контент-план:", lang),
        "cntpln_load": translate("Контент-план успешно загружен", lang),
        "cp_err": translate("Ошибка загрузки контент-плана:", lang),
        "cntpln_load_error": translate("Ошибка при загрузке контент-плана", lang),
        "server_resp": translate("Ответ от сервера:", lang),
        "post_suc_upd": translate("Пост успешно обновлён", lang),
        "planned_for": translate("Пост успешно запланирован на", lang),
        "cont_plan_gen": translate("Генерация контент-плана", lang),
        "ard_data": translate("Ошибка при отправке данных", lang),
        "cp_send": translate("Контент-план успешно отправлен", lang),
    }
