from project.language import translate, language


def settings(request):
    lang = language(request)
    return {
        "profile": translate("Профиль", lang),
        "groups": translate("Группы", lang),
        "notifications": translate("Уведомления", lang),
        "personal_info": translate("Личная информация", lang),
        "change_photo": translate("Изменить фото", lang),
        "name": translate("Имя", lang),
        "surname": translate("Фамилия", lang),
        "phone": translate("Телефон", lang),
        "change_password": translate("Изменение пароля", lang),
        "current_password": translate("Текущий пароль", lang),
        "new_password": translate("Новый пароль", lang),
        "confirm_password": translate("Подтверждение пароля", lang),
        "pwd_requirements": translate("Требования к паролю", lang),
        "minimum_characters": translate("Минимум 8 символов", lang),
        "capital_letter": translate("Хотя бы одна заглавная буква", lang),
        "at_least_one_digit": translate("Хотя бы одна цифра", lang),
        "special_character": translate("Хотя бы один специальный символ", lang),
        "account_settings": translate("Настройки аккаунта", lang),
        "interface_language": translate("Язык интерфейса", lang),
        "russian": translate("Русский", lang),
        "english": "English",
        "time_zone": translate("Часовой пояс", lang),
        "moscow": translate("Москва", lang),
        "kaliningrad": translate("Калининград", lang),
        "samara": translate("Самара", lang),
        "ekaterinburg": translate("Екатеринбург", lang),
        "omsk": translate("Омск", lang),
        "krasnoyarsk": translate("Красноярск", lang),
        "irkutsk": translate("Иркутск", lang),
        "yakutsk": translate("Якутск", lang),
        "vladivostok": translate("Владивосток", lang),
        "magadan": translate("Магадан", lang),
        "kamchatka": translate("Камчатка", lang),
        "add_group": translate("Добавить группу", lang),
        "dark_mode": translate("Тёмная тема", lang),
        "connected_groups": translate("Подключённые группы", lang),
        "active": translate("Активные", lang),
        "inactive": translate("Неактивные", lang),
        "reset": translate("Сбросить", lang),
        "search_by_name": translate("Поиск по названию", lang),
        "notification_settings": translate("Настройки уведомлений", lang),
        "email_notifications": translate("Email уведомления", lang),
        "new_posts": translate("Новые посты", lang),
        "new_generated_posts": translate("Получать уведомления о новых сгенерированных постах", lang),
        "publishing_posts": translate("Публикация постов", lang),
        "notifications_about_publication": translate("Получать уведомления о публикации постов в группах", lang),
        "using_coins": translate("Использование коинов", lang),
        "low_balance": translate("Получать уведомления о низком балансе", lang),
        "payments_and_subscription": translate("Платежи и подписка", lang),
        "subscription_changes": translate("Получать уведомления о платежах и изменениях в подписке", lang),
        "news_and_updates": translate("Новости и обновления", lang),
        "service_updates": translate("Получать информацию о новых функциях и обновлениях сервиса", lang),
        "browser_notifications": translate("Браузерные уведомления", lang),
        "enable_browser_notifications": translate("Включить браузерные уведомления", lang),
        "allow_sending_notifications": translate("Разрешить отправку уведомлений в браузере", lang),
        "telegram_notifications": translate("Telegram уведомления", lang),
        "your_telegram": translate("Ваш Telegram", lang),
        "connect": translate("Подключить", lang),
        "instant_notifications": translate("Подключите ваш Telegram для получения мгновенных уведомлений", lang),
        "save_settings": translate("Сохранить настройки", lang),
        "adding_public": translate("Добавление группы", lang),
        "select_platform": translate("Выберите платформу", lang),
        "group_id_address": translate("ID группы или адрес", lang),
        "full_page_address": translate("Укажите ID группы или полный адрес страницы", lang),
        "group_name_optional": translate("Название группы (опционально)", lang),
        "authorization": translate("Авторизация", lang),
        "vk_login": translate("Авторизоваться через ВКонтакте", lang),
        "required_to_publish": translate("Необходимо для публикации постов в группе", lang),
        "i_am_the_admin": translate("Я являюсь администратором этой группы", lang),
        "public_name": translate("Имя канала или группы", lang),
        "with_the_symbol": translate("Укажите имя канала или группы с символом @", lang),
        "bot_token": translate("Токен бота", lang),
        "paste_received_token": translate("Создайте бота через @BotFather и вставьте полученный токен", lang),
        "bot_is_admin_your_channel": translate("Не забудьте добавить созданного бота в качестве администратора вашего канала или группы", lang),
        "valid_username": translate("Пожалуйста, введите действительное имя пользователя Telegram, начинающееся с @", lang),
        "sucs_notices": translate("Вы успешно подписались на уведомления Telegram!", lang),
        "error": translate("Error", lang),
        "succ_pay": translate("Оплата прошла успешно", lang),
        "error_occurred": translate("При обработке вашего запроса произошла ошибка.", lang),
        "are_you_sure": translate("Вы уверены, что хотите удалить эту группу?", lang),
        "error_data_sending": translate("Произошла ошибка при отправке данных", lang),
    }
