"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os, sys

# Загружаем .env файл
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PUBLIC_HOST = os.getenv('PUBLIC_HOST')

PROJECT_ROOT = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'False'

ALLOWED_HOST = os.getenv('ALLOWED_HOST')

PUBLIC_HOST = os.getenv('PUBLIC_HOST')

ALLOWED_HOSTS = [PUBLIC_HOST, ALLOWED_HOST]

 # Redirect URI приложения VK
VK_REDIRECT_URI = os.getenv('VK_REDIRECT_URI')
 # Клиентский ID приложения VK
SOCIAL_AUTH_VK_OAUTH2_KEY = os.getenv('VK_CLIENT_ID')
 # Секретный ключ приложения VK
SOCIAL_AUTH_VK_OAUTH2_SECRET = os.getenv('VK_CLIENT_SECRET')
 # Запрашиваем разрешения на доступ к email
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']
 # Подтверждаем редирект на https
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'apps.login.apps.LoginConfig',
    'whitenoise.runserver_nostatic',
    'apps.basetmp.apps.BasetmpConfig',
    'apps.vkoauth.apps.VKoauthConfig',
    'apps.posting.apps.PostingConfig',
    'apps.articles.apps.ArticlesConfig',
    'apps.settings.apps.SettingsConfig',
    'apps.mainpage.apps.MainpageConfig',
    'apps.subscribe.apps.SubscribeConfig',
    'apps.generation.apps.GenerationConfig'
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'apps.basetmp.context_processors.menu_context',
                'apps.posting.context_processors.scheduler',
                'apps.posting.context_processors.settings',
                'apps.posting.context_processors.all_posts',
                'apps.posting.context_processors.create_post',
                'apps.subscribe.context_processors.subscription',
                'apps.login.context_processors.login_page',
                'apps.login.context_processors.reset_page',
                'project.context_processors.dark_mode',
                'apps.generation.context_processors.autogeneration',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

CSRF_TRUSTED_ORIGINS = [
    "https://devfront.groupposter.ru",
]

CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = True
LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian'),
]

TIME_ZONE = 'UTC'

USE_TZ = True

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_FILE_PATH = BASE_DIR / 'sessions'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
