from project.language import translate, language


def subscription(request):
    lang = language(request)
    return {
        "current_sub": translate("Текущая подписка", lang),
        "plan": translate("Тариф", lang),
        "coins_per_month": translate("коинов в месяц", lang),
        "start_date": translate("Дата начала", lang),
        "next_payment": translate("Следующее списание", lang),
        "price": translate("Стоимость", lang),
        "payment": translate("Способ оплаты", lang),
        "month": translate("месяц", lang),
        "next_write_off": translate("Дата следующего списания", lang),
        "click_to_confirm": translate("Нажимая 'Подтвердить', вы соглашаетесь с условиями использования сервиса и подтверждаете", lang),
        "will_be_debited_from_your_card": translate("что с вашей карты будет списана указанная сумма", lang),
        "payment_period": translate("Период оплаты", lang),
        "coins_using": translate("Использование коинов", lang),
        "coins_aval": translate("Доступно коинов", lang),
        "consumption": translate("Расход коинов", lang),
        "active": translate("Активна", lang),
        "confirm": translate("Подтвердить", lang),
        "posts_gen": translate("Генерация постов", lang),
        "coins": translate("коинов", lang),
        "groups_an": translate("Анализ групп", lang),
        "images_gen": translate("Генерация изображений", lang),
        "add_coins": translate("Купить дополнительные коины", lang),
        "cancel_subs": translate("Отменить подписку", lang),
        "change_plan": translate("Изменить тариф", lang),
        "available_planes": translate("Доступные тарифы", lang),
        "annually": translate("Ежегодно", lang),
        "profi": translate("Профи", lang),
        "monthly_payment": translate("Ежемесячная оплата", lang),
        "annual_payment": translate("Ежегодная оплата", lang),
        "discount": translate("скидка", lang),
        "upgrade_to": translate("Обновить до", lang),
        "annual_plan": translate("годовой план", lang),
        "note": translate("Примечание", lang),
        "all_plans_include": translate("Все тарифы включают неограниченное", lang),
        "number_of_requests": translate("количество запросов", lang),
        "within_limits": translate("в пределах доступных коинов", lang),
        "paying_annually": translate("При оплате за год предоставляется", lang),
        "discount_provided": translate("дополнительная скидка", lang),
        "individual_rate": translate("Нужен индивидуальный тариф", lang),
        "for_your_company": translate("для вашей компании", lang),
        "corporate_offer": translate("Получить корпоративное предложение", lang),
        "payment_history": translate("История платежей", lang),
        "no_payment_data": translate("Нет данных о платежах", lang),
        "date": translate("Дата", lang),
        "tariff_update_confirmation": translate("Подтверждение обновления тарифа", lang),
        "your_choose_plan": translate("Вы выбрали тариф", lang),
        "sum": translate("Сумма", lang),
        "status": translate("Статус", lang),
        "check": translate("Чек", lang),
        "subscription": translate("Подписка", lang),
        "paid": translate("Оплачено", lang),
        "paid_his": translate("История платежей, навигация", lang),
        "prew": translate("Предыдущая", lang),
        "next": translate("Следующая", lang),
        "payment_methods": translate("Способы оплаты", lang),
        "add_payment_method": translate("Добавить способ оплаты", lang),
        "validity_period": translate("Срок действия", lang),
        "main": translate("Основная", lang),
        "make_main": translate("Сделать основной", lang),
        "faq": translate("Часто задаваемые вопросы", lang),
        "how_coins_work": translate("Как работает система коинов?", lang),
        "internal_currency": translate("Коины — это внутренняя валюта", lang),
        "which_is_used": translate("которая используется для оплаты", lang),
        "various_functions": translate("различных функций сервиса", lang),
        "plan_includes": translate("Каждый тариф включает", lang),
        "certain_number ": translate("определенное количество коинов в месяц", lang),
        "сoins_spent_on": translate("Коины расходуются на", lang),
        "generation_of_posts": translate("генерацию постов", lang),
        "group_analysis": translate("анализ групп", lang),
        "image_creation": translate("создание изображений", lang),
        "and_other_functions": translate("и другие функции", lang),
        "have_enough_coins": translate("Если вам не хватает коинов", lang),
        "purchase_additional": translate("вы всегда можете приобрести дополнительные", lang),
        "how_can_change": translate("Как изменить тариф подписки?", lang),
        "howto_cancel_subscription": translate("Как отменить подписку?", lang),
        "roll_over": translate("Переносятся ли неиспользованные коины на следующий месяц?", lang),
        "invoice_for_accounting": translate("Как получить счет-фактуру для бухгалтерии?", lang),
        "need_help": translate("Нужна помощь?", lang),
        "write_to_support": translate("Написать в поддержку", lang),
        "help_center": translate("Центр помощи", lang),
        "adding_payment_method": translate("Добавление способа оплаты", lang),
        "card_num": translate("Номер карты", lang),
        "cardholder_name": translate("Имя владельца карты", lang),
        "make_main_payment_method": translate("Сделать основным способом оплаты", lang),
        "add": translate("Добавить", lang),
        "cancel_subscription": translate("Отмена подписки", lang),
        "cancel_subscription_confirm": translate("Вы уверены, что хотите отменить подписку?", lang),
        "cancel_subscription_options": translate("При отмене подписки", lang),
        "will_be_active_until": translate("Ваша подписка будет активна до", lang),
        "automatic_renewal_disabled": translate("Автоматическое продление будет отключено", lang),
        "use_all_functions": translate("Вы сможете использовать все функции", lang),
        "before_expiration": translate("до окончания срока действия", lang),
        "renew_subscription": translate("Вы можете возобновить подписку в любое время", lang),
        "reason_for_cancel": translate("Причина отмены (необязательно)", lang),
        "select_reason": translate("Выберите причину", lang),
        "too_expensive": translate("Слишком дорого", lang),
        "not_use_service": translate("Не использую сервис", lang),
        "missing_features": translate("Не хватает функций", lang),
        "found_alternative": translate("Нашёл альтернативу", lang),
        "other": translate("Другое", lang),
        "write_reason": translate("Укажите причину", lang),
        "сonfirm_unsubscription": translate("Подтвердить отмену подписки", lang),
        "successfully_renewed": translate("Ваша подписка успешно возобновлена", lang),
        "will_be_cancelled": translate("Ваша подписка будет отменена по окончании текущего периода", lang),
        "reason": translate("Причина", lang),
        "will_cancelled": translate("Будет отменена", lang),
        "no_saved_cards": translate("Нет сохранённых карт", lang),
        "money_saving": translate("Экономия", lang),
        "enter_card_number": translate("Введите действительный номер карты (13–19 цифр)", lang),
        "enter_card_period": translate("Введите срок действия в формате ММ / ГГ", lang),
        "enter_card_cvv": translate("Введите корректный CVV (3 цифры)", lang),
        "enter_cardholder_name": translate("Введите имя держателя карты", lang),
        "error_processing_form": translate("Ошибка обработки формы", lang),
        "unknown_error": translate("Неизвестная ошибка", lang),
        "error_subscr": translate("Произошла ошибка при возобновлении подписки", lang),
        "error_sending_form": translate("Ошибка отправки формы", lang),
        "error_cancel": translate("Произошла ошибка при отмене подписки", lang),
        "reason_required": translate("Пожалуйста, выберите причину отмены", lang),
        "add_coins_sign": translate("Добавить коины", lang),
        "enter_coins_num": translate("Введите количество коинов для покупки", lang),
    }
