from project.language import translate, language


def all_posts(request):
    lang = language(request)
    return {
        "title": translate("Мои посты", lang),
        "h2_text": translate("Мои посты", lang),
        "exit": translate("Выйти", lang),
        "by_date": translate("По дате", lang),
        "all_dates": translate("Все даты", lang),
        "today": translate("Сегодня", lang),
        "last_7_days": translate("Последние 7 дней", lang),
        "last_30_days": translate("Последние 30 дней", lang),
        "last_90_days": translate("Последние 90 дней", lang),
        "new_first": translate("Сначала новые", lang),
        "old_first": translate("Сначала старые", lang),
        "all_platforms": translate("Все платформы", lang),
        "vk": translate("Вконтакте", lang),
        "tg": translate("Телеграм", lang),
        "email": "Email",
        "boosty": translate("Бусти", lang),
        "all_statuses": translate("Все статусы", lang),
        "publish": translate("Опубликовано", lang),
        "draft": translate("Черновик", lang),
        "queue": translate("В очереди", lang),
        "delete_button": translate("Удалить", lang),
        "publish_text": translate("Публикация", lang),
        "edit_button": translate("Редактировать", lang),
        "load_more_text": translate("Загрузить ещё", lang),
        "no_more_posts_text": translate("Больше постов нет", lang),
        "post_title": translate("Заголовок", lang),
        "post_descr": translate("Описание", lang),
        "platform": translate("Платформа", lang),
        "pub_date": translate("Дата публикации", lang),
        "image": translate("Изображение", lang),
        "status": translate("Статус", lang),
        "empty": translate("Оставьте пустым для немедленной публикации", lang),
        "cancel": translate("Отмена", lang),
        "save_changes": translate("Сохранить изменения", lang),
        "shure": translate("Вы уверены, что хотите удалить этот пост? Это действие нельзя будет отменить", lang),
        "del_confirm": translate("Подтверждение удаления", lang),
        "post_editing": translate("Редактирование поста", lang),
    }

def autogeneration(request):
    lang = language(request)
    return {
        "group_selection": translate("Выбор группы", lang),
        "analysis": translate("Анализ", lang),
        "topics": translate("Темы", lang),
        "content_plan": translate("Контент-план", lang),
        "posts": translate("Посты", lang),
        "card_title": translate("Выберите группу для анализа", lang),
        "group_analysis": translate("Анализ группы", lang),
        "selected_group": translate("Выбранная группа", lang),
        "subscribers": translate("Подписчиков", lang),
        "add_new_group": translate("Добавить новую группу", lang),
        "add_for_analysis": translate("Подключите новую группу или страницу для анализа", lang),
        "next": translate("Далее", lang),
        "back_to_posts": translate("Назад к постам", lang),
        "marketing": translate("Маркетинг и реклама", lang),
        "interior_design": translate("Дизайн интерьера", lang),
        "it_and_technologys": translate("IT и технологии", lang),
        "analyses_cost": translate("Стоимость анализа", lang),
        "group_cost": translate("Анализ этой группы будет стоить", lang),
        "coins": translate("коинов", lang),
        "run_analysis": translate("Запустить анализ группы", lang),
        "analysis_complete": translate("Анализ завершён!", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),
        "analysis": translate("Анализ", lang),

    }