from project.language import translate, language


def all_posts(request):
    lang = language(request)
    return {
        "title": translate("Мои посты", lang),
        "h2_text": translate("Мои посты", lang),
        "exit": translate("Выйти", lang),
        "by_date": translate("По дате", lang),
        "all_dates": translate("Все даты", lang),
        "today": translate("Сегодня", lang),
        "last_7_days": translate("Последние 7 дней", lang),
        "last_30_days": translate("Последние 30 дней", lang),
        "last_90_days": translate("Последние 90 дней", lang),
        "new_first": translate("Сначала новые", lang),
        "old_first": translate("Сначала старые", lang),
        "all_platforms": translate("Все платформы", lang),
        "vk": translate("Вконтакте", lang),
        "tg": translate("Телеграм", lang),
        "email": "Email",
        "boosty": translate("Бусти", lang),
        "all_statuses": translate("Все статусы", lang),
        "published": translate("Опубликовано", lang),
        "draft": translate("Черновик", lang),
        "queue": translate("В очереди", lang),
        "delete_button": translate("Удалить", lang),
        "publish_text": translate("Публикация", lang),
        "edit_button": translate("Редактировать", lang),
        "load_more_text": translate("Загрузить ещё", lang),
        "no_more_posts_text": translate("Больше постов нет", lang),
        "post_title": translate("Заголовок", lang),
        "post_descr": translate("Описание", lang),
        "platform": translate("Платформа", lang),
        "pub_date": translate("Дата публикации", lang),
        "image": translate("Изображение", lang),
        "status": translate("Статус", lang),
        "empty": translate("Оставьте пустым для немедленной публикации", lang),
        "cancel": translate("Отмена", lang),
        "save_changes": translate("Сохранить изменения", lang),
        "shure": translate("Вы уверены, что хотите удалить этот пост? Это действие нельзя будет отменить", lang),
        "del_confirm": translate("Подтверждение удаления", lang),
        "post_editing": translate("Редактирование поста", lang),
    }


def create_post(request):
    lang = language(request)
    return {
        "post_title_2": translate("Заголовок поста", lang),
        "should_be": translate("Заголовок должен быть информативным и привлекательным", lang),
        "platform": translate("Платформа", lang),
        "post_content": translate("Содержание поста", lang),
        "max_length": translate("Максимальная длина", lang),
        "max_length_num": 2000,
        "characters_for": translate("символов для", lang),
        "network": "LinkedIn",
        "post_image": translate("Изображение поста", lang),
        "image_drop": translate("Перетащите изображение сюда или", lang),
        "choose_file": translate("выберите файл", lang),
        "or": translate("или", lang),
        "max": translate("максимум", lang),
        "ai_generation": translate("Сгенерировать с помощью ИИ", lang),
        "choice": translate("Или выберите из предложенных", lang),
        "pub_settings": translate("Настройки публикации", lang),
        "schedule_post": translate("Запланировать публикацию", lang),
        "pub_time": translate("Время публикации", lang),
        "save_as_draft": translate("Сохранить как черновик", lang),
        "allow_comments": translate("Разрешить комментарии", lang),
        "hashtags": translate("Хэштеги", lang),
        "add_hashtags": translate("Добавьте релевантные хэштеги для увеличения охвата", lang),
        "preview": translate("Предпросмотр", lang),
        "generate": translate("Сгенерировать", lang),
        "save_draft": translate("Сохранить как черновик", lang),
        "publish": translate("Опубликовать", lang),
        "post_preview": translate("Предпросмотр поста", lang),
        "post_title": translate("Заголовок поста", lang),
        "post_content_here": translate("Содержание поста будет отображаться здесь", lang),
        "close": translate("Закрыть", lang),
        "gen_ai": translate("Генерация поста с помощью ИИ", lang),
        "what_post": translate("Опишите, какой пост вы хотите создать", lang),
        "gen_par": translate("Параметры генерации", lang),
        "style": translate("Стиль", lang),
        "professional": translate("Профессиональный", lang),
        "friendly": translate("Дружелюбный", lang),
        "informal": translate("Неформальный", lang),
        "enthusiastic": translate("Энтузиастичный", lang),
        "informative": translate("Информативный", lang),
        "length": translate("Длина", lang),
        "short": translate("Короткий (100-200 слов)", lang),
        "medium": translate("Средний (200-400 слов)", lang),
        "long": translate("Длинный (400-600 слов)", lang),
        "loading": translate("Загрузка", lang),
        "post_generation": translate("Генерация поста", lang),
        "generated_post": translate("Сгенерированный пост", lang),
        "regenerate": translate("Сгенерировать заново", lang),
        "use": translate("Использовать", lang),
        "сoins_used": translate("Использовано коинов", lang),
        "cancel": translate("Отмена", lang),
        "size_must": translate("Размер файла не должен превышать 5MB", lang),
        "enter_title": translate("Пожалуйста, введите заголовок поста", lang),
        "enter_content": translate("Пожалуйста, введите содержание поста", lang),
        "incorrect_pub_date": translate("Дата публикации не верна", lang),
        "success_publish": translate("Пост успешно опубликован", lang),
        "draft_saved": translate("Черновик успешно сохранён", lang),
        "planed": translate("Пост запланирован к публикации", lang),
        "ai_image_gen": translate("Генерация изображения с ИИ", lang),
        "describe": translate("Опишите желаемое изображение", lang),
        "example_1": translate("Например: Профессиональный бизнесмен", lang),
        "example_2": translate("в офисе работает за компьютером,", lang),
        "example_3": translate("современный стиль, яркие цвета", lang),
        "image_style": translate("Стиль изображения", lang),
        "realistic": translate("Реалистичный", lang),
        "cartoon": translate("Мультяшный", lang),
        "abstract": translate("Абстрактный", lang),
        "ratio": translate("Соотношение сторон", lang),
        "square": translate("1:1 (квадрат)", lang),
        "add_hashtag": translate("Добавьте хэштег и нажмите Enter", lang),
        "add_request": translate("Пожалуйста, введите запрос для генерации", lang),
        "enter_url": translate("Введите URL", lang),
        "enter_description": translate("Пожалуйста, введите описание для генерации изображения", lang),
        "enter_post_title": translate("Введите заголовок поста", lang),
        "enter_post_content": translate("Введите содержание поста", lang),
        "ratio_16_9": '16:9',
        "ratio_4_3": '4:3',
        "gen_result": translate("Результат генерации", lang),
        "image_gen": translate("Генерация изображения", lang),
        "30_second_to_mars": translate("Это может занять до 30 секунд", lang),
        "use_image": translate("Использовать изображение", lang),
    }


def scheduler(request):
    lang = language(request)
    return {
        "by_pub_date": translate("По дате публикации", lang),
        "tomorrow": translate("Завтра", lang),
        "this_week": translate("Эта неделя", lang),
        "next_week": translate("Следующая неделя", lang),
        "nearest_first": translate("Сначала ближайшие", lang),
        "latest_first": translate("Сначала последние", lang),
        "all_platforms": translate("Все платформы", lang),
        "add_to_queue": translate("Добавить в очередь", lang),
        "pub_cal": translate("Календарь публикаций", lang),
        "schad_pub": translate("Календарь запланированных публикаций", lang),
        "up_pub": translate("Ближайшие публикации", lang),
        "planed": translate("Запланировано", lang),
        "for_next_week": translate("на следующую неделю", lang),
        "for_next_month": translate("на следующий месяц", lang),
        "without_image": translate("Без изображения", lang),
        "change_date": translate("Изменить дату", lang),
        "publish_now": translate("Опубликовать сейчас", lang),
        "change_pub_date": translate("Изменить дату публикации", lang),
        "pub_date_time": translate("Дата и время публикации", lang),
        "repeat_pub": translate("Повторять публикацию", lang),
        "not_repeat": translate("Не повторять", lang),
        "daily": translate("Ежедневно", lang),
        "weekly": translate("Еженедельно", lang),
        "monthly": translate("Ежемесячно", lang),
        "save": translate("Сохранить", lang),
        "right_now": translate("Вы уверены, что хотите опубликовать этот пост прямо сейчас?", lang),
    }


def subscription(request):
    lang = language(request)
    return {
        "current_sub": translate("Текущая подписка", lang),
        "plan": translate("Тариф", lang),
        "coins_per_month": translate("коинов в месяц", lang),
        "start_date": translate("Дата начала", lang),
        "next_payment": translate("Следующее списание", lang),
        "price": translate("Стоимость", lang),
        "payment": translate("Способ оплаты", lang),
        "month": translate("месяц", lang),
        "coins_using": translate("Использование коинов", lang),
        "coins_aval": translate("Доступно коинов", lang),
        "consumption": translate("Расход коинов", lang),
        "active": translate("Активна", lang),
        "posts_gen": translate("Генерация постов", lang),
        "coins": translate("коинов", lang),
        "groups_an": translate("Анализ групп", lang),
        "images_gen": translate("Генерация изображений", lang),
        "add_coins": translate("Купить дополнительные коины", lang),
        "cancel_subs": translate("Отменить подписку", lang),
        "change_plan": translate("Изменить тариф", lang),
        "available_planes": translate("Доступные тарифы", lang),
        "annually": translate("Ежегодно", lang),
        "profi": translate("Профи", lang),
        "monthly_payment": translate("Ежемесячная оплата", lang),
        "annual_payment": translate("Ежегодная оплата", lang),
        "discount": translate("скидка", lang),
        "upgrade_to": translate("Обновить до", lang),
        "annual_plan": translate("годовой план", lang),
        "note": translate("Примечание", lang),
        "all_plans_include": translate("Все тарифы включают неограниченное", lang),
        "number_of_requests": translate("количество запросов", lang),
        "within_limits": translate("в пределах доступных коинов", lang),
        "paying_annually": translate("При оплате за год предоставляется", lang),
        "discount_provided": translate("дополнительная скидка", lang),
        "individual_rate": translate("Нужен индивидуальный тариф", lang),
        "for_your_company": translate("для вашей компании", lang),
        "corporate_offer": translate("Получить корпоративное предложение", lang),
        "payment_history": translate("История платежей", lang),
        "date": translate("Дата", lang),
        "sum": translate("Сумма", lang),
        "status": translate("Статус", lang),
        "check": translate("Чек", lang),
        "subscription": translate("Подписка", lang),
        "paid": translate("Оплачено", lang),
        "paid_his": translate("История платежей, навигация", lang),
        "prew": translate("Предыдущая", lang),
        "next": translate("Следующая", lang),
        "payment_methods": translate("Способы оплаты", lang),
        "add_payment_method": translate("Добавить способ оплаты", lang),
        "validity_period": translate("Срок действия", lang),
        "main": translate("Основная", lang),
        "make_main": translate("Сделать основной", lang),
        "faq": translate("Часто задаваемые вопросы", lang),
        "how_coins_work": translate("Как работает система коинов?", lang),
        "internal_currency": translate("Коины — это внутренняя валюта", lang),
        "which_is_used": translate("которая используется для оплаты", lang),
        "various_functions": translate("различных функций сервиса", lang),
        "plan_includes": translate("Каждый тариф включает", lang),
        "certain_number ": translate("определенное количество коинов в месяц", lang),
        "сoins_spent_on": translate("Коины расходуются на", lang),
        "generation_of_posts": translate("генерацию постов", lang),
        "group_analysis": translate("анализ групп", lang),
        "image_creation": translate("создание изображений", lang),
        "and_other_functions": translate("и другие функции", lang),
        "have_enough_coins": translate("Если вам не хватает коинов", lang),
        "purchase_additional": translate("вы всегда можете приобрести дополнительные", lang),
        "how_can_change": translate("Как изменить тариф подписки?", lang),
        "howto_cancel_subscription": translate("Как отменить подписку?", lang),
        "roll_over": translate("Переносятся ли неиспользованные коины на следующий месяц?", lang),
        "invoice_for_accounting": translate("Как получить счет-фактуру для бухгалтерии?", lang),
        "need_help": translate("Нужна помощь?", lang),
        "write_to_support": translate("Написать в поддержку", lang),
        "help_center": translate("Центр помощи", lang),
        "adding_payment_method": translate("Добавление способа оплаты", lang),
        "card_num": translate("Номер карты", lang),
        "cardholder_name": translate("Имя владельца карты", lang),
        "make_main_payment_method": translate("Сделать основным способом оплаты", lang),
        "add": translate("Добавить", lang),
        "cancel_subscription": translate("Отмена подписки", lang),
        "cancel_subscription_confirm": translate("Вы уверены, что хотите отменить подписку?", lang),
        "cancel_subscription_options": translate("При отмене подписки", lang),
        "will_be_active_until": translate("Ваша подписка будет активна до", lang),
        "automatic_renewal_disabled": translate("Автоматическое продление будет отключено", lang),
        "use_all_functions": translate("Вы сможете использовать все функции", lang),
        "before_expiration": translate("до окончания срока действия", lang),
        "renew_subscription": translate("Вы можете возобновить подписку в любое время", lang),
        "reason_for_cancel": translate("Причина отмены (необязательно)", lang),
        "select_reason": translate("Выберите причину", lang),
        "too_expensive": translate("Слишком дорого", lang),
        "not_use_service": translate("Не использую сервис", lang),
        "missing_features": translate("Не хватает функций", lang),
        "found_alternative": translate("Нашёл альтернативу", lang),
        "other": translate("Другое", lang),
        "write_reason": translate("Укажите причину", lang),
        "сonfirm_unsubscription": translate("Подтвердить отмену подписки", lang),
        "successfully_renewed": translate("Ваша подписка успешно возобновлена", lang),
        "will_be_cancelled": translate("Ваша подписка будет отменена по окончании текущего периода", lang),
        "reason": translate("Причина", lang),
        "will_cancelled": translate("Будет отменена", lang),
    }

def settings(request):
    lang = language(request)
    return {
        "profile": translate("Профиль", lang),
        "groups": translate("Группы", lang),
        "notifications": translate("Уведомления", lang),
        "personal_info": translate("Личная информация", lang),
        "change_photo": translate("Изменить фото", lang),
        "name": translate("Имя", lang),
        "surname": translate("Фамилия", lang),
        "phone": translate("Телефон", lang),
        "change_password": translate("Изменение пароля", lang),
        "current_password": translate("Текущий пароль", lang),
        "new_password": translate("Новый пароль", lang),
        "confirm_password": translate("Подтверждение пароля", lang),
        "pwd_requirements": translate("Требования к паролю", lang),
        "minimum_characters": translate("Минимум 8 символов", lang),
        "capital_letter": translate("Хотя бы одна заглавная буква", lang),
        "at_least_one_digit": translate("Хотя бы одна цифра", lang),
        "special_character": translate("Хотя бы один специальный символ", lang),
        "account_settings": translate("Настройки аккаунта", lang),
        "interface_language": translate("Язык интерфейса", lang),
        "russian": translate("Русский", lang),
        "english": "English",
        "time_zone": translate("Часовой пояс", lang),
        "moscow": translate("Москва", lang),
        "kaliningrad": translate("Калининград", lang),
        "samara": translate("Самара", lang),
        "ekaterinburg": translate("Екатеринбург", lang),
        "omsk": translate("Омск", lang),
        "krasnoyarsk": translate("Красноярск", lang),
        "irkutsk": translate("Иркутск", lang),
        "yakutsk": translate("Якутск", lang),
        "vladivostok": translate("Владивосток", lang),
        "magadan": translate("Магадан", lang),
        "kamchatka": translate("Камчатка", lang),
        "add_group": translate("Добавить группу", lang),
        "dark_mode": translate("Тёмная тема", lang),
        "connected_groups": translate("Подключённые группы", lang),
        "active": translate("Активные", lang),
        "inactive": translate("Неактивные", lang),
        "reset": translate("Сбросить", lang),
        "search_by_name": translate("Поиск по названию", lang),
        "notification_settings": translate("Настройки уведомлений", lang),
        "email_notifications": translate("Email уведомления", lang),
        "new_posts": translate("Новые посты", lang),
        "new_generated_posts": translate("Получать уведомления о новых сгенерированных постах", lang),
        "publishing_posts": translate("Публикация постов", lang),
        "notifications_about_publication": translate("Получать уведомления о публикации постов в группах", lang),
        "using_coins": translate("Использование коинов", lang),
        "low_balance": translate("Получать уведомления о низком балансе", lang),
        "payments_and_subscription": translate("Платежи и подписка", lang),
        "subscription_changes": translate("Получать уведомления о платежах и изменениях в подписке", lang),
        "news_and_updates": translate("Новости и обновления", lang),
        "service_updates": translate("Получать информацию о новых функциях и обновлениях сервиса", lang),
        "browser_notifications": translate("Браузерные уведомления", lang),
        "enable_browser_notifications": translate("Включить браузерные уведомления", lang),
        "allow_sending_notifications": translate("Разрешить отправку уведомлений в браузере", lang),
        "telegram_notifications": translate("Telegram уведомления", lang),
        "your_telegram": translate("Ваш Telegram", lang),
        "connect": translate("Подключить", lang),
        "instant_notifications": translate("Подключите ваш Telegram для получения мгновенных уведомлений", lang),
        "save_settings": translate("Сохранить настройки", lang),
        "adding_public": translate("Добавление группы", lang),
        "select_platform": translate("Выберите платформу", lang),
        "group_id_address": translate("ID группы или адрес", lang),
        "full_page_address": translate("Укажите ID группы или полный адрес страницы", lang),
        "group_name_optional": translate("Название группы (опционально)", lang),
        "authorization": translate("Авторизация", lang),
        "vk_login": translate("Авторизоваться через ВКонтакте", lang),
        "required_to_publish": translate("Необходимо для публикации постов в группе", lang),
        "i_am_the_admin": translate("Я являюсь администратором этой группы", lang),
        "public_name": translate("Имя канала или группы", lang),
        "with_the_symbol": translate("Укажите имя канала или группы с символом @", lang),
        "bot_token": translate("Токен бота", lang),
        "paste_received_token": translate("Создайте бота через @BotFather и вставьте полученный токен", lang),
        "bot_is_admin_your_channel": translate("Не забудьте добавить созданного бота в качестве администратора вашего канала или группы", lang),
    }